Add step for installing pandas & small grammar fix
When running the `tdbpy importcsv` command, I received the error:
```
ImportError: Library 'pandas' is required to import csv, either install 'pandas' or install woqlDataframe requirements as follows: python -m pip install -U terminus-client-python[dataframe]
```
Additional grammar nit - it's more correct to import 'a CSV file', not 'a CSV'.